#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const root = process.cwd()
const checkOnly = process.argv.includes('--check')
const pending = []

function readJson(path) {
  return JSON.parse(readFileSync(join(root, path), 'utf8'))
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

function fit(value, width) {
  const text = String(value)
  if (text.length > width) return `${text.slice(0, width - 3)}...`
  return text.padEnd(width, ' ')
}

function blockRow(left, right) {
  return `| ${fit(left, 31)} | ${fit(right, 32)} |`
}

function writeGenerated(path, content) {
  const absolute = join(root, path)
  const normalized = content.endsWith('\n') ? content : `${content}\n`
  if (checkOnly) {
    if (!existsSync(absolute) || readFileSync(absolute, 'utf8') !== normalized) {
      pending.push(path)
    }
    return
  }
  mkdirSync(dirname(absolute), { recursive: true })
  writeFileSync(absolute, normalized, 'utf8')
}

const connector = readJson('tools/foundry-connector/connector-manifest.json')
const q5 = readJson('tools/q5-adr-parser/adr_manifest.json')
const statuses = new Map(q5.records.map((record) => [record.id, record.status]))

const ascii = [
  '/* FOUNDRY INTEL :: BACKEND ASCII GLITCH PAGE */',
  '/* Generated by tools/ascii-glitch/build-pages.mjs */',
  '',
  '+------------------------------------------------------------------------+',
  '| THE SHARED PRIMORDIAL FOUNDATION                                       |',
  "| Foundry Intel, in care of Bel Esprit D'Accord                         |",
  '+-------------------------------+----------------------------------------+',
  blockRow('repo', connector.repos.foundry_intel.repo),
  blockRow('branch', connector.repos.foundry_intel.branch),
  blockRow('connector', connector.status),
  blockRow('pages', connector.pages?.status ?? 'STATIC_READY'),
  blockRow('rebrand', connector.rebrand.status),
  blockRow('governing ADR', connector.rebrand.governing_adr),
  blockRow('Q(phi) total', q5.q5_total),
  blockRow('ADR-055', statuses.get('ADR-055')),
  blockRow('ADR-062', statuses.get('ADR-062')),
  '+-------------------------------+----------------------------------------+',
  '',
  'GKN-LEAN-LATCH     >>== theorem anchors ==>>',
  '       ||',
  '       \\\\/',
  '[ FOUNDRY-INTEL ] -- ADR -- XML -- WORM -- BOB -- PAGES',
  '       /\\\\',
  '       ||',
  'FOUNDRY-F1-RT      <<== runtime evidence ==<<',
  '',
  '   .--.      .--.      .--.      .--.      .--.',
  '  /_00_\\____/_01_\\____/_02_\\____/_03_\\____/_04_\\',
  '  \\____/    \\____/    \\____/    \\____/    \\____/',
  '     | SOURCE | DATALOG | LEAN | TRUST | WORM |',
  '   .--.      .--.      .--.      .--.      .--.',
  '  /_05_\\____/_06_\\____/_07_\\____/_08_\\____/_09_\\',
  '  \\____/    \\____/    \\____/    \\____/    \\____/',
  '     | BOB | METATRON | PROBE | LH | ADR-301 |',
  '',
  'glitch discipline:',
  '  0000 evidence enters       1111 silence blocks',
  '  0101 open crux stays open  1010 WORM stays append-only',
  '  0110 pages render static   1001 frontend can dock later',
  '',
  'do not promote:',
  `  ADR-055 = ${statuses.get('ADR-055')}`,
  `  ADR-062 = ${statuses.get('ADR-062')}`,
  '  Q(phi) = metadata, not proof',
  '',
  'end transmission.'
].join('\n')

const css = [
  ':root {',
  '  color-scheme: dark;',
  '  --ink: #f4f1de;',
  '  --muted: #9fb3c8;',
  '  --line: #314155;',
  '  --panel: #10161d;',
  '  --panel-2: #141b24;',
  '  --bg: #080b10;',
  '  --amber: #f2b84b;',
  '  --cyan: #4dd8c8;',
  '  --rose: #ff5f73;',
  '  --green: #8bd17c;',
  '}',
  '',
  '* { box-sizing: border-box; }',
  'html { min-height: 100%; background: var(--bg); }',
  'body {',
  '  margin: 0;',
  '  min-height: 100%;',
  '  color: var(--ink);',
  '  background: #080b10;',
  '  font: 15px/1.55 ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;',
  '}',
  'body::before {',
  '  content: "";',
  '  position: fixed;',
  '  inset: 0;',
  '  pointer-events: none;',
  '  opacity: 0.18;',
  '  background-image: repeating-linear-gradient(0deg, transparent 0 7px, #ffffff 8px);',
  '}',
  '',
  '.shell { width: min(1120px, calc(100vw - 32px)); margin: 0 auto; padding: 32px 0 48px; }',
  '.topline { display: flex; justify-content: space-between; gap: 16px; color: var(--muted); }',
  '.stamp { color: var(--green); }',
  'h1 { margin: 18px 0 8px; font-size: clamp(2rem, 7vw, 5rem); line-height: 0.95; letter-spacing: 0; }',
  '.subtitle { max-width: 820px; color: var(--muted); font-size: 1rem; }',
  '.grid { display: grid; grid-template-columns: minmax(0, 1.25fr) minmax(280px, 0.75fr); gap: 18px; margin-top: 26px; }',
  '.panel { border: 1px solid var(--line); background: var(--panel); border-radius: 8px; overflow: hidden; }',
  '.panel h2 { margin: 0; padding: 12px 14px; color: var(--amber); font-size: 0.9rem; border-bottom: 1px solid var(--line); background: var(--panel-2); }',
  'pre { margin: 0; padding: 16px; overflow: auto; min-height: 420px; color: var(--cyan); text-shadow: 1px 0 var(--rose); }',
  '.map { width: 100%; display: block; background: #0c1117; }',
  '.facts { display: grid; grid-template-columns: 1fr; gap: 0; }',
  '.fact { display: flex; justify-content: space-between; gap: 14px; padding: 12px 14px; border-top: 1px solid var(--line); }',
  '.fact:first-child { border-top: 0; }',
  '.fact b { color: var(--ink); }',
  '.fact span { color: var(--muted); text-align: right; overflow-wrap: anywhere; }',
  '.route { margin-top: 18px; border: 1px solid var(--line); border-radius: 8px; background: #0d131a; padding: 14px; color: var(--muted); }',
  '.route strong { color: var(--green); }',
  '@media (max-width: 840px) {',
  '  .topline { flex-direction: column; }',
  '  .grid { grid-template-columns: 1fr; }',
  '  h1 { font-size: 2.25rem; }',
  '  pre { min-height: 300px; }',
  '}'
].join('\n')

const html = [
  '<!doctype html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1">',
  '  <title>Foundry Intel Backend ASCII Glitch</title>',
  '  <meta name="description" content="Static backend ASCII/glitch page for Foundry Intel governance and Primordial Foundation transition.">',
  '  <link rel="stylesheet" href="assets/backend-glitch.css">',
  '</head>',
  '<body>',
  '  <main class="shell">',
  '    <div class="topline">',
  `      <span>${escapeHtml(connector.repos.foundry_intel.repo)}</span>`,
  `      <span class="stamp">${escapeHtml(connector.status)} / ${escapeHtml(connector.rebrand.status)}</span>`,
  '    </div>',
  '    <h1>Backend ASCII Glitch</h1>',
  '    <p class="subtitle">Static Pages surface for the Foundry Intel governance hub. It renders the backend trust spine, connector state, and open-crux boundaries while the frontend can dock separately.</p>',
  '    <section class="grid" aria-label="Backend page surface">',
  '      <div class="panel">',
  '        <h2>terminal signal</h2>',
  `        <pre>${escapeHtml(ascii)}</pre>`,
  '      </div>',
  '      <aside class="panel">',
  '        <h2>connector facts</h2>',
  '        <div class="facts">',
  `          <div class="fact"><b>Q(phi)</b><span>${escapeHtml(q5.q5_total)}</span></div>`,
  `          <div class="fact"><b>ADR-055</b><span>${escapeHtml(statuses.get('ADR-055'))}</span></div>`,
  `          <div class="fact"><b>ADR-062</b><span>${escapeHtml(statuses.get('ADR-062'))}</span></div>`,
  `          <div class="fact"><b>rebrand</b><span>${escapeHtml(connector.rebrand.governing_adr)}</span></div>`,
  `          <div class="fact"><b>handoff</b><span>${escapeHtml(connector.handoff.status)}</span></div>`,
  '        </div>',
  '        <img class="map" src="../brand/foundry-intel-operating-map.svg" alt="Foundry Intel operating map">',
  '      </aside>',
  '    </section>',
  '    <div class="route"><strong>route:</strong> GKN Lean latch -&gt; Foundry Intel ADR/Q(phi)/XML/WORM/BOB -&gt; Foundry F1 receiver -&gt; evidence returns before claims become final.</div>',
  '  </main>',
  '</body>',
  '</html>'
].join('\n')

writeGenerated('docs/pages/backend-ascii.txt', ascii)
writeGenerated('docs/pages/assets/backend-glitch.css', css)
writeGenerated('docs/pages/index.html', html)

if (pending.length > 0) {
  console.error('pages check failed: generated files are stale')
  for (const path of pending) console.error(`  ${path}`)
  process.exit(1)
}

console.log(checkOnly ? 'pages check passed' : 'pages built')
